### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Yz2019** [nanoxas/sketch-to-terrain#2]
Hello，I have read your code. But I have one question. what' s the meaning of the ` noise = Input((K.int_shape(conv5)[1], K.int_shape(conv5)[2], K.int_shape(conv5)[3]))` in the Unet() function?

**Comment by nanoxas** [comment]
Hi, the purpose of the noise input is for the model to be able to model the distribution of DEMs given a sketch. Since the input does not fully determine the output there is a distribution of probability in that problem. You need the noise to sample the learned distribution which is being learned by the model.
